### ISSUE TITLE
Easy auto-update

### ISSUE THREAD

**Issue by vitorgalvao** [arthurhammer/alfred-workflows#1]
I see you have `auto-update` as one of the suggested improvements for your [Help workflow](https://github.com/arthurhammer/alfred-workflows/tree/master/help), but you say you won’t necessarily implement it.

I know how bothersome adding auto-updating features to Alfred workflows is, which is why I made [OneUpdater](http://www.alfredforum.com/topic/9224-oneupdater-%E2%80%94-update-workflows-with-a-single-node/). In just a few quick steps, you can have an updater up and running and you will be able to set it and forget it. That is to say you configure it once (you’ll really need to change only two values) and it’ll work on it’s own without further intervention.

If you ever want to get rid of it, you just delete its node, and it’s done.

Take a look at it, if you want. If you have any doubts or need help implementing it, just ask.

**Comment by arthurhammer** [comment]
Thank you for your suggestions, Vítor! 👍 I'll have a look at your solution soon. Auto-updating was actually one of the items I did plan to implement.
